import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import './globals.css';
import { cn } from '@/src/shared/lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const montserrat = Montserrat({ subsets: ['latin'] });

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen antialiased flex flex-col',
          montserrat.className,
        )}
      >
        {children}
      </body>
    </html>
  );
};
export default RootLayout;
